name: firebase_version_repository
description: "Firebase Version Repository"
version: 1.0.0

publish_to: https://forgejo.internal.iconica.nl/api/packages/internal/pub/

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: any
  version_repository_interface:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^1.0.0
  shared_preferences: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_iconica_analysis:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub/
    version: ^7.0.0
