name: example
description: "Flutter Version Manager Example"
publish_to: 'none' 
# Change these versions to show various scenarios of versioning in the example
version: 0.1.0+1
backend-version: 1.0.0

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: any
  cloud_firestore: any
  flutter_version_manager:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^0.1.0
  firebase_version_repository:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_iconica_analysis:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub/
    version: ^7.0.0

flutter:
  uses-material-design: true
  assets:
    - pubspec.yaml

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
